### PR TITLE
resolves: 103 create workflow for running benchmarks

### LINKED ISSUE #103: create workflow for running benchmarks
The workflow should take as input: 
- machines config : JSON with list of individual machine configs. (As a girder file ID)
- single app-use_case config file specifying application related configurations. (As a girder file ID)

machine selection and image pulling must be done in gaya runner.

### PR DESCRIPTION
**Pull request by JavierCladellas**
- Closes #103

Main changes: 
- Created the `benchmark.yml` workflow that launches the tests on a given machine (via configs on girder), and creates a PR (containing only docs) with the new benchmark reports. 
- Added some scripts used by the ci under _src/feelpp/scripts/_

⚠️ NOTE ⚠️  
It has only been tested on gaya, with a builtin config and apptainer config. Apptainer config seems to have a bug concerning MPI bindings, but this bug should be independent of the pipeline.

### CODE REVIEW

**Comment by JavierCladellas** [comment]
Merge #94 before.

**Comment by JavierCladellas** [comment]
@prudhomm @vincentchabannes Benchmarks can now be triggered (after workflow is in master) via repository and workflow dispatch by providing the machines and benchmark json configs via a girder ID. 

Apptainer is not ready yet: bug related with mpi 

Parameters are:  
- machines_config : girder ID of the machine list containing system specific configuration (e.g. https://girder.math.unistra.fr/#item/6720f5a8b0e95728eb010af4)
- benchmark_config: girder ID of the benchmark/application specific configuration (e.g. https://girder.math.unistra.fr/#item/672cbe4db0e95728eb010b8e)

**Review by prudhomm — APPROVED** [review]
There are some hard coded paths, we need at some point in the future to change this

**Comment by prudhomm** [comment]
@JavierCladellas isn't it possible to split the json describing the benchmark and avoid duplicating eg the plot section between apptainer and builting ?

**Comment by JavierCladellas** [comment]
> @JavierCladellas isn't it possible to split the json describing the benchmark and avoid duplicating eg the plot section between apptainer and builting ?

This is already done in #109 . The benchmark configuration should now be modified as little as possible. Also, plots section will be moved to a separate file in #111

**Pull request merged**
