### PR TITLE
resolves: 101 do not store adoc files in git tree

### LINKED ISSUE #101: Do not store adoc files in git tree
- [ ] Remove rendered adoc files from git
- [ ] Handle previewing files with netlify

### PR DESCRIPTION
**Pull request by JavierCladellas**
- Closes #101 

Done:
- [x] Removed all reports that were stored under the git repository (_reports/_ and _docs/pages/*_)
- [x] Netlify will itself create the adoc reports under _docs/modules/ROOT/pages_ for preview
- [x] Removed the `generate_reports` step of the CI, as we don't want any pushes. 
- [x] On push to master, the GitHub runner in the CI will create the reports, antora will compile them under _public/_, and the deploy to gh pages will be handled as usual. No major changes...

### CODE REVIEW

**Comment by JavierCladellas** [comment]
@prudhomm Is it possible to add the girder api key to Netlify's environment ?

**Comment by prudhomm** [comment]
Yes simply add the Installation command in the netlify script

**Comment by prudhomm** [comment]
Oops yes, i can add env variable. I will do that when i come back

**Comment by JavierCladellas** [comment]
> Oops yes, i can add env variable. I will do that when i come back

@prudhomm Small reminder (not urgent) to add the `GIRDER_API_KEY` variable in netlify's environment. Thank you !

**Comment by prudhomm** [comment]
@JavierCladellas there are conflicts here. GIRDER_API_KEY has now been defined

**Comment by JavierCladellas** [comment]
> @JavierCladellas there are conflicts here. GIRDER_API_KEY has now been defined

Everything seems to be working as expected! Netlify renders the files by itself. 
The .adoc files and the reframe reports are no longer stored in the GitHub repo. 
@prudhomm @vincentchabannes

**Review by vincentchabannes — APPROVED** [review]

**Pull request merged**
